name: CI & CD
on:
  push:
    branches:
      - main 

jobs:
  combined:
    name: Test & build
    runs-on: ubuntu-latest
    # env:
    #   FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # modern usage
    steps:
      - name: Get the code
        uses: 'actions/checkout@v4'

      # - name: Uses nodejs v20
      #   uses: 'actions/setup-node@v4'
      #   with:
      #     node-version: 20
      #     cache: npm
      
      - name: install dependencies
        #run: npm ci 
        run: yarn install --frozen-lockfile
      
      # - name: Run unit tests
      #   run: npm test

      # - name: Run end-to-end tests
      #   run: npx cypress run

      - name: build the app
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
            

  deploy:
    needs: combined
    runs-on: ubuntu-lastest
    steps:
      - name: deplod app to o2switch
        run: echo "deploing..."
  
      

